import { ComponentType } from "react";
import Image from "next/image";

interface SearchType {
  label: string;
  value: string;
  icon: ComponentType;
}

export const colors: SearchType[] = [
  {
    value: "W",
    label: "White",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/W.svg" alt="White" width={16} height={16} />,  },
  {
    value: "U",
    label: "Blue",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/U.svg" alt="Blue" width={16} height={16} />,
  },
  {
    value: "B",
    label: "Black",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/B.svg" alt="Black" width={16} height={16} />,
  },
  {
    value: "R",
    label: "Red",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/R.svg" alt="Red" width={16} height={16} />,
  },
  {
    value: "G",
    label: "Green",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/G.svg" alt="Green" width={16} height={16} />,
  },
  {
    value: "C",
    label: "Colorless",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/C.svg" alt="Colorless" width={16} height={16} />,
  },
  {
    value: "S",
    label: "Snow",
    icon: () => <Image src="https://svgs.scryfall.io/card-symbols/S.svg" alt="Snow" width={16} height={16} />,
  },
];

export const cardTypes = [
  { label: 'Artifact', value: 'Artifact', group: 'Types' },
  { label: 'Battle', value: 'Battle', group: 'Types' },
  { label: 'Conspiracy', value: 'Conspiracy', group: 'Types' },
  { label: 'Creature', value: 'Creature', group: 'Types' },
  { label: 'Dungeon', value: 'Dungeon', group: 'Types' },
  { label: 'Emblem', value: 'Emblem', group: 'Types' },
  { label: 'Enchantment', value: 'Enchantment', group: 'Types' },
  { label: 'Hero', value: 'Hero', group: 'Types' },
  { label: 'Instant', value: 'Instant', group: 'Types' },
  { label: 'Kindred', value: 'Kindred', group: 'Types' },
  { label: 'Land', value: 'Land', group: 'Types' },
  { label: 'Phenomenon', value: 'Phenomenon', group: 'Types' },
  { label: 'Plane', value: 'Plane', group: 'Types' },
  { label: 'Planeswalker', value: 'Planeswalker', group: 'Types' },
  { label: 'Scheme', value: 'Scheme', group: 'Types' },
  { label: 'Sorcery', value: 'Sorcery', group: 'Types' },
  { label: 'Vanguard', value: 'Vanguard', group: 'Types' },
  { label: 'Basic', value: 'Basic', group: 'Supertypes' },
  { label: 'Elite', value: 'Elite', group: 'Supertypes' },
  { label: 'Legendary', value: 'Legendary', group: 'Supertypes' },
  { label: 'Ongoing', value: 'Ongoing', group: 'Supertypes' },
  { label: 'Snow', value: 'Snow', group: 'Supertypes' },
  { label: 'Token', value: 'Token', group: 'Supertypes' },
  { label: 'World', value: 'World', group: 'Supertypes' },
  { label: 'Attraction', value: 'Attraction', group: 'Artifact Types' },
  { label: 'Blood', value: 'Blood', group: 'Artifact Types' },
  { label: 'Bobblehead', value: 'Bobblehead', group: 'Artifact Types' },
  { label: 'Clue', value: 'Clue', group: 'Artifact Types' },
  { label: 'Contraption', value: 'Contraption', group: 'Artifact Types' },
  { label: 'Equipment', value: 'Equipment', group: 'Artifact Types' },
  { label: 'Food', value: 'Food', group: 'Artifact Types' },
  { label: 'Fortification', value: 'Fortification', group: 'Artifact Types' },
  { label: 'Gold', value: 'Gold', group: 'Artifact Types' },
  { label: 'Incubator', value: 'Incubator', group: 'Artifact Types' },
  { label: 'Junk', value: 'Junk', group: 'Artifact Types' },
  { label: 'Map', value: 'Map', group: 'Artifact Types' },
  { label: 'Powerstone', value: 'Powerstone', group: 'Artifact Types' },
  { label: 'Treasure', value: 'Treasure', group: 'Artifact Types' },
  { label: 'Vehicle', value: 'Vehicle', group: 'Artifact Types' },
  { label: 'Aura', value: 'Aura', group: 'Enchantment Types' },
  { label: 'Background', value: 'Background', group: 'Enchantment Types' },
  { label: 'Cartouche', value: 'Cartouche', group: 'Enchantment Types' },
  { label: 'Case', value: 'Case', group: 'Enchantment Types' },
  { label: 'Class', value: 'Class', group: 'Enchantment Types' },
  { label: 'Curse', value: 'Curse', group: 'Enchantment Types' },
  { label: 'Role', value: 'Role', group: 'Enchantment Types' },
  { label: 'Room', value: 'Room', group: 'Enchantment Types' },
  { label: 'Rune', value: 'Rune', group: 'Enchantment Types' },
  { label: 'Saga', value: 'Saga', group: 'Enchantment Types' },
  { label: 'Shard', value: 'Shard', group: 'Enchantment Types' },
  { label: 'Shrine', value: 'Shrine', group: 'Enchantment Types' },
  { label: 'Cave', value: 'Cave', group: 'Land Types' },
  { label: 'Cloud', value: 'Cloud', group: 'Land Types' },
  { label: 'Desert', value: 'Desert', group: 'Land Types' },
  { label: 'Forest', value: 'Forest', group: 'Land Types' },
  { label: 'Gate', value: 'Gate', group: 'Land Types' },
  { label: 'Island', value: 'Island', group: 'Land Types' },
  { label: 'Lair', value: 'Lair', group: 'Land Types' },
  { label: 'Locus', value: 'Locus', group: 'Land Types' },
  { label: 'Mine', value: 'Mine', group: 'Land Types' },
  { label: 'Mountain', value: 'Mountain', group: 'Land Types' },
  { label: 'Sphere', value: 'Sphere', group: 'Land Types' },
  { label: 'Plains', value: 'Plains', group: 'Land Types' },
  { label: 'Power-Plant', value: 'Power-Plant', group: 'Land Types' },
  { label: 'Swamp', value: 'Swamp', group: 'Land Types' },
  { label: 'Tower', value: 'Tower', group: 'Land Types' },
  { label: 'Urza\'s', value: 'Urza\'s', group: 'Land Types' },
  { label: 'Adventure', value: 'Adventure', group: 'Spell Types' },
  { label: 'Arcane', value: 'Arcane', group: 'Spell Types' },
  { label: 'Chorus', value: 'Chorus', group: 'Spell Types' },
  { label: 'Lesson', value: 'Lesson', group: 'Spell Types' },
  { label: 'Trap', value: 'Trap', group: 'Spell Types' },
  { label: 'Abian', value: 'Abian', group: 'Planeswalker Types' },
  { label: 'Ajani', value: 'Ajani', group: 'Planeswalker Types' },
  { label: 'Aminatou', value: 'Aminatou', group: 'Planeswalker Types' },
  { label: 'Angrath', value: 'Angrath', group: 'Planeswalker Types' },
  { label: 'Arlinn', value: 'Arlinn', group: 'Planeswalker Types' },
  { label: 'Ashiok', value: 'Ashiok', group: 'Planeswalker Types' },
  { label: 'B.O.B.', value: 'B.O.B.', group: 'Planeswalker Types' },
  { label: 'Bahamut', value: 'Bahamut', group: 'Planeswalker Types' },
  { label: 'Basri', value: 'Basri', group: 'Planeswalker Types' },
  { label: 'Bolas', value: 'Bolas', group: 'Planeswalker Types' },
  { label: 'Calix', value: 'Calix', group: 'Planeswalker Types' },
  { label: 'Chandra', value: 'Chandra', group: 'Planeswalker Types' },
  { label: 'Comet', value: 'Comet', group: 'Planeswalker Types' },
  { label: 'Dack', value: 'Dack', group: 'Planeswalker Types' },
  { label: 'Dakkon', value: 'Dakkon', group: 'Planeswalker Types' },
  { label: 'Daretti', value: 'Daretti', group: 'Planeswalker Types' },
  { label: 'Davriel', value: 'Davriel', group: 'Planeswalker Types' },
  { label: 'Deb', value: 'Deb', group: 'Planeswalker Types' },
  { label: 'Dihada', value: 'Dihada', group: 'Planeswalker Types' },
  { label: 'Domri', value: 'Domri', group: 'Planeswalker Types' },
  { label: 'Dovin', value: 'Dovin', group: 'Planeswalker Types' },
  { label: 'Duck', value: 'Duck', group: 'Planeswalker Types' },
  { label: 'Dungeon', value: 'Dungeon', group: 'Planeswalker Types' },
  { label: 'Ellywick', value: 'Ellywick', group: 'Planeswalker Types' },
  { label: 'Elminster', value: 'Elminster', group: 'Planeswalker Types' },
  { label: 'Elspeth', value: 'Elspeth', group: 'Planeswalker Types' },
  { label: 'Equipment', value: 'Equipment', group: 'Planeswalker Types' },
  { label: 'Ersta', value: 'Ersta', group: 'Planeswalker Types' },
  { label: 'Estrid', value: 'Estrid', group: 'Planeswalker Types' },
  { label: 'Freyalise', value: 'Freyalise', group: 'Planeswalker Types' },
  { label: 'Garruk', value: 'Garruk', group: 'Planeswalker Types' },
  { label: 'Gideon', value: 'Gideon', group: 'Planeswalker Types' },
  { label: 'Grist', value: 'Grist', group: 'Planeswalker Types' },
  { label: 'Guff', value: 'Guff', group: 'Planeswalker Types' },
  { label: 'Huatli', value: 'Huatli', group: 'Planeswalker Types' },
  { label: 'Inzerva', value: 'Inzerva', group: 'Planeswalker Types' },
  { label: 'Jace', value: 'Jace', group: 'Planeswalker Types' },
  { label: 'Jared', value: 'Jared', group: 'Planeswalker Types' },
  { label: 'Jaya', value: 'Jaya', group: 'Planeswalker Types' },
  { label: 'Jeska', value: 'Jeska', group: 'Planeswalker Types' },
  { label: 'Kaito', value: 'Kaito', group: 'Planeswalker Types' },
  { label: 'Karn', value: 'Karn', group: 'Planeswalker Types' },
  { label: 'Kasmina', value: 'Kasmina', group: 'Planeswalker Types' },
  { label: 'Kaya', value: 'Kaya', group: 'Planeswalker Types' },
  { label: 'Kiora', value: 'Kiora', group: 'Planeswalker Types' },
  { label: 'Koth', value: 'Koth', group: 'Planeswalker Types' },
  { label: 'Liliana', value: 'Liliana', group: 'Planeswalker Types' },
  { label: 'Lolth', value: 'Lolth', group: 'Planeswalker Types' },
  { label: 'Lukka', value: 'Lukka', group: 'Planeswalker Types' },
  { label: 'Luxior', value: 'Luxior', group: 'Planeswalker Types' },
  { label: 'Master', value: 'Master', group: 'Planeswalker Types' },
  { label: 'Minsc', value: 'Minsc', group: 'Planeswalker Types' },
  { label: 'Mordenkainen', value: 'Mordenkainen', group: 'Planeswalker Types' },
  { label: 'Nahiri', value: 'Nahiri', group: 'Planeswalker Types' },
  { label: 'Narset', value: 'Narset', group: 'Planeswalker Types' },
  { label: 'Niko', value: 'Niko', group: 'Planeswalker Types' },
  { label: 'Nissa', value: 'Nissa', group: 'Planeswalker Types' },
  { label: 'Nixilis', value: 'Nixilis', group: 'Planeswalker Types' },
  { label: 'Oko', value: 'Oko', group: 'Planeswalker Types' },
  { label: 'Quintorius', value: 'Quintorius', group: 'Planeswalker Types' },
  { label: 'Ral', value: 'Ral', group: 'Planeswalker Types' },
  { label: 'Rowan', value: 'Rowan', group: 'Planeswalker Types' },
  { label: 'Saheeli', value: 'Saheeli', group: 'Planeswalker Types' },
  { label: 'Samut', value: 'Samut', group: 'Planeswalker Types' },
  { label: 'Sarkhan', value: 'Sarkhan', group: 'Planeswalker Types' },
  { label: 'Serra', value: 'Serra', group: 'Planeswalker Types' },
  { label: 'Sivitri', value: 'Sivitri', group: 'Planeswalker Types' },
  { label: 'Sorin', value: 'Sorin', group: 'Planeswalker Types' },
  { label: 'Svega', value: 'Svega', group: 'Planeswalker Types' },
  { label: 'Szat', value: 'Szat', group: 'Planeswalker Types' },
  { label: 'Tamiyo', value: 'Tamiyo', group: 'Planeswalker Types' },
  { label: 'Tasha', value: 'Tasha', group: 'Planeswalker Types' },
  { label: 'Teferi', value: 'Teferi', group: 'Planeswalker Types' },
  { label: 'Teyo', value: 'Teyo', group: 'Planeswalker Types' },
  { label: 'Tezzeret', value: 'Tezzeret', group: 'Planeswalker Types' },
  { label: 'Tibalt', value: 'Tibalt', group: 'Planeswalker Types' },
  { label: 'Tyvar', value: 'Tyvar', group: 'Planeswalker Types' },
  { label: 'Ugin', value: 'Ugin', group: 'Planeswalker Types' },
  { label: 'Urza', value: 'Urza', group: 'Planeswalker Types' },
  { label: 'Venser', value: 'Venser', group: 'Planeswalker Types' },
  { label: 'Vivien', value: 'Vivien', group: 'Planeswalker Types' },
  { label: 'Vraska', value: 'Vraska', group: 'Planeswalker Types' },
  { label: 'Vronos', value: 'Vronos', group: 'Planeswalker Types' },
  { label: 'Wanderer', value: 'Wanderer', group: 'Planeswalker Types' },
  { label: 'Will', value: 'Will', group: 'Planeswalker Types' },
  { label: 'Windgrace', value: 'Windgrace', group: 'Planeswalker Types' },
  { label: 'Wrenn', value: 'Wrenn', group: 'Planeswalker Types' },
  { label: 'Xenagos', value: 'Xenagos', group: 'Planeswalker Types' },
  { label: 'Yanggu', value: 'Yanggu', group: 'Planeswalker Types' },
  { label: 'Yanling', value: 'Yanling', group: 'Planeswalker Types' },
  { label: 'Zariel', value: 'Zariel', group: 'Planeswalker Types' },
  { label: 'Advisor', value: 'Advisor', group: 'Creature Types' },
  { label: 'Aetherborn', value: 'Aetherborn', group: 'Creature Types' },
  { label: 'Alicorn', value: 'Alicorn', group: 'Creature Types' },
  { label: 'Alien', value: 'Alien', group: 'Creature Types' },
  { label: 'Ally', value: 'Ally', group: 'Creature Types' },
  { label: 'Angel', value: 'Angel', group: 'Creature Types' },
  { label: 'Antelope', value: 'Antelope', group: 'Creature Types' },
  { label: 'Ape', value: 'Ape', group: 'Creature Types' },
  { label: 'Archer', value: 'Archer', group: 'Creature Types' },
  { label: 'Archon', value: 'Archon', group: 'Creature Types' },
  { label: 'Armadillo', value: 'Armadillo', group: 'Creature Types' },
  { label: 'Armored', value: 'Armored', group: 'Creature Types' },
  { label: 'Army', value: 'Army', group: 'Creature Types' },
  { label: 'Art', value: 'Art', group: 'Creature Types' },
  { label: 'Artificer', value: 'Artificer', group: 'Creature Types' },
  { label: 'Assassin', value: 'Assassin', group: 'Creature Types' },
  { label: 'Assembly-Worker', value: 'Assembly-Worker', group: 'Creature Types' },
  { label: 'Astartes', value: 'Astartes', group: 'Creature Types' },
  { label: 'Athlete', value: 'Athlete', group: 'Creature Types' },
  { label: 'Atog', value: 'Atog', group: 'Creature Types' },
  { label: 'Aurochs', value: 'Aurochs', group: 'Creature Types' },
  { label: 'Autobot', value: 'Autobot', group: 'Creature Types' },
  { label: 'Automaton', value: 'Automaton', group: 'Creature Types' },
  { label: 'Avatar', value: 'Avatar', group: 'Creature Types' },
  { label: 'Azra', value: 'Azra', group: 'Creature Types' },
  { label: 'Baddest,', value: 'Baddest,', group: 'Creature Types' },
  { label: 'Badger', value: 'Badger', group: 'Creature Types' },
  { label: 'Balloon', value: 'Balloon', group: 'Creature Types' },
  { label: 'Barbarian', value: 'Barbarian', group: 'Creature Types' },
  { label: 'Bard', value: 'Bard', group: 'Creature Types' },
  { label: 'Basilisk', value: 'Basilisk', group: 'Creature Types' },
  { label: 'Bat', value: 'Bat', group: 'Creature Types' },
  { label: 'Bear', value: 'Bear', group: 'Creature Types' },
  { label: 'Beast', value: 'Beast', group: 'Creature Types' },
  { label: 'Beaver', value: 'Beaver', group: 'Creature Types' },
  { label: 'Beeble', value: 'Beeble', group: 'Creature Types' },
  { label: 'Beholder', value: 'Beholder', group: 'Creature Types' },
  { label: 'Berserker', value: 'Berserker', group: 'Creature Types' },
  { label: 'Biggest,', value: 'Biggest,', group: 'Creature Types' },
  { label: 'Bird', value: 'Bird', group: 'Creature Types' },
  { label: 'Blinkmoth', value: 'Blinkmoth', group: 'Creature Types' },
  { label: 'Boar', value: 'Boar', group: 'Creature Types' },
  { label: 'Boxer', value: 'Boxer', group: 'Creature Types' },
  { label: 'Brainiac', value: 'Brainiac', group: 'Creature Types' },
  { label: 'Bringer', value: 'Bringer', group: 'Creature Types' },
  { label: 'Brushwagg', value: 'Brushwagg', group: 'Creature Types' },
  { label: 'Bureaucrat', value: 'Bureaucrat', group: 'Creature Types' },
  { label: 'C\'tan', value: 'C\'tan', group: 'Creature Types' },
  { label: 'Camarid', value: 'Camarid', group: 'Creature Types' },
  { label: 'Camel', value: 'Camel', group: 'Creature Types' },
  { label: 'Capybara', value: 'Capybara', group: 'Creature Types' },
  { label: 'Caribou', value: 'Caribou', group: 'Creature Types' },
  { label: 'Carrier', value: 'Carrier', group: 'Creature Types' },
  { label: 'Cat', value: 'Cat', group: 'Creature Types' },
  { label: 'Centaur', value: 'Centaur', group: 'Creature Types' },
  { label: 'Cephalid', value: 'Cephalid', group: 'Creature Types' },
  { label: 'Chameleon', value: 'Chameleon', group: 'Creature Types' },
  { label: 'Champion', value: 'Champion', group: 'Creature Types' },
  { label: 'Chef', value: 'Chef', group: 'Creature Types' },
  { label: 'Chicken', value: 'Chicken', group: 'Creature Types' },
  { label: 'Child', value: 'Child', group: 'Creature Types' },
  { label: 'Chimera', value: 'Chimera', group: 'Creature Types' },
  { label: 'Citizen', value: 'Citizen', group: 'Creature Types' },
  { label: 'Clamfolk', value: 'Clamfolk', group: 'Creature Types' },
  { label: 'Cleric', value: 'Cleric', group: 'Creature Types' },
  { label: 'Clown', value: 'Clown', group: 'Creature Types' },
  { label: 'Cockatrice', value: 'Cockatrice', group: 'Creature Types' },
  { label: 'Construct', value: 'Construct', group: 'Creature Types' },
  { label: 'Cow', value: 'Cow', group: 'Creature Types' },
  { label: 'Coward', value: 'Coward', group: 'Creature Types' },
  { label: 'Coyote', value: 'Coyote', group: 'Creature Types' },
  { label: 'Crab', value: 'Crab', group: 'Creature Types' },
  { label: 'Crocodile', value: 'Crocodile', group: 'Creature Types' },
  { label: 'Custodes', value: 'Custodes', group: 'Creature Types' },
  { label: 'Cyberman', value: 'Cyberman', group: 'Creature Types' },
  { label: 'Cyborg', value: 'Cyborg', group: 'Creature Types' },
  { label: 'Cyclops', value: 'Cyclops', group: 'Creature Types' },
  { label: 'Dalek', value: 'Dalek', group: 'Creature Types' },
  { label: 'Dauthi', value: 'Dauthi', group: 'Creature Types' },
  { label: 'Deer', value: 'Deer', group: 'Creature Types' },
  { label: 'Demigod', value: 'Demigod', group: 'Creature Types' },
  { label: 'Demon', value: 'Demon', group: 'Creature Types' },
  { label: 'Deserter', value: 'Deserter', group: 'Creature Types' },
  { label: 'Designer', value: 'Designer', group: 'Creature Types' },
  { label: 'Detective', value: 'Detective', group: 'Creature Types' },
  { label: 'Devil', value: 'Devil', group: 'Creature Types' },
  { label: 'Dinosaur', value: 'Dinosaur', group: 'Creature Types' },
  { label: 'Djinn', value: 'Djinn', group: 'Creature Types' },
  { label: 'Doctor', value: 'Doctor', group: 'Creature Types' },
  { label: 'Dog', value: 'Dog', group: 'Creature Types' },
  { label: 'Donkey', value: 'Donkey', group: 'Creature Types' },
  { label: 'Dragon', value: 'Dragon', group: 'Creature Types' },
  { label: 'Drake', value: 'Drake', group: 'Creature Types' },
  { label: 'Dreadnought', value: 'Dreadnought', group: 'Creature Types' },
  { label: 'Drone', value: 'Drone', group: 'Creature Types' },
  { label: 'Druid', value: 'Druid', group: 'Creature Types' },
  { label: 'Dryad', value: 'Dryad', group: 'Creature Types' },
  { label: 'Dwarf', value: 'Dwarf', group: 'Creature Types' },
  { label: 'Efreet', value: 'Efreet', group: 'Creature Types' },
  { label: 'Egg', value: 'Egg', group: 'Creature Types' },
  { label: 'Elder', value: 'Elder', group: 'Creature Types' },
  { label: 'Eldrazi', value: 'Eldrazi', group: 'Creature Types' },
  { label: 'Elemental', value: 'Elemental', group: 'Creature Types' },
  { label: 'Elemental?', value: 'Elemental?', group: 'Creature Types' },
  { label: 'Elephant', value: 'Elephant', group: 'Creature Types' },
  { label: 'Elf', value: 'Elf', group: 'Creature Types' },
  { label: 'Elk', value: 'Elk', group: 'Creature Types' },
  { label: 'Elves', value: 'Elves', group: 'Creature Types' },
  { label: 'Employee', value: 'Employee', group: 'Creature Types' },
  { label: 'Etiquette', value: 'Etiquette', group: 'Creature Types' },
  { label: 'Eye', value: 'Eye', group: 'Creature Types' },
  { label: 'Faerie', value: 'Faerie', group: 'Creature Types' },
  { label: 'Ferret', value: 'Ferret', group: 'Creature Types' },
  { label: 'Fish', value: 'Fish', group: 'Creature Types' },
  { label: 'Flagbearer', value: 'Flagbearer', group: 'Creature Types' },
  { label: 'Fox', value: 'Fox', group: 'Creature Types' },
  { label: 'Fractal', value: 'Fractal', group: 'Creature Types' },
  { label: 'Frog', value: 'Frog', group: 'Creature Types' },
  { label: 'Fungus', value: 'Fungus', group: 'Creature Types' },
  { label: 'Gamer', value: 'Gamer', group: 'Creature Types' },
  { label: 'Gargoyle', value: 'Gargoyle', group: 'Creature Types' },
  { label: 'Germ', value: 'Germ', group: 'Creature Types' },
  { label: 'Giant', value: 'Giant', group: 'Creature Types' },
  { label: 'Gith', value: 'Gith', group: 'Creature Types' },
  { label: 'Glimmer', value: 'Glimmer', group: 'Creature Types' },
  { label: 'Gnoll', value: 'Gnoll', group: 'Creature Types' },
  { label: 'Gnome', value: 'Gnome', group: 'Creature Types' },
  { label: 'Goat', value: 'Goat', group: 'Creature Types' },
  { label: 'Goblin', value: 'Goblin', group: 'Creature Types' },
  { label: 'God', value: 'God', group: 'Creature Types' },
  { label: 'Golem', value: 'Golem', group: 'Creature Types' },
  { label: 'Gorgon', value: 'Gorgon', group: 'Creature Types' },
  { label: 'Grandchild', value: 'Grandchild', group: 'Creature Types' },
  { label: 'Graveborn', value: 'Graveborn', group: 'Creature Types' },
  { label: 'Gremlin', value: 'Gremlin', group: 'Creature Types' },
  { label: 'Griffin', value: 'Griffin', group: 'Creature Types' },
  { label: 'Guest', value: 'Guest', group: 'Creature Types' },
  { label: 'Gus', value: 'Gus', group: 'Creature Types' },
  { label: 'Hag', value: 'Hag', group: 'Creature Types' },
  { label: 'Halfling', value: 'Halfling', group: 'Creature Types' },
  { label: 'Hamster', value: 'Hamster', group: 'Creature Types' },
  { label: 'Harpy', value: 'Harpy', group: 'Creature Types' },
  { label: 'Hatificer', value: 'Hatificer', group: 'Creature Types' },
  { label: 'Hawk', value: 'Hawk', group: 'Creature Types' },
  { label: 'Head', value: 'Head', group: 'Creature Types' },
  { label: 'Hellion', value: 'Hellion', group: 'Creature Types' },
  { label: 'Hero', value: 'Hero', group: 'Creature Types' },
  { label: 'Hippo', value: 'Hippo', group: 'Creature Types' },
  { label: 'Hippogriff', value: 'Hippogriff', group: 'Creature Types' },
  { label: 'Homarid', value: 'Homarid', group: 'Creature Types' },
  { label: 'Homunculus', value: 'Homunculus', group: 'Creature Types' },
  { label: 'Hornet', value: 'Hornet', group: 'Creature Types' },
  { label: 'Horror', value: 'Horror', group: 'Creature Types' },
  { label: 'Horse', value: 'Horse', group: 'Creature Types' },
  { label: 'Human', value: 'Human', group: 'Creature Types' },
  { label: 'Hydra', value: 'Hydra', group: 'Creature Types' },
  { label: 'Hyena', value: 'Hyena', group: 'Creature Types' },
  { label: 'Illusion', value: 'Illusion', group: 'Creature Types' },
  { label: 'Imp', value: 'Imp', group: 'Creature Types' },
  { label: 'Incarnation', value: 'Incarnation', group: 'Creature Types' },
  { label: 'Inkling', value: 'Inkling', group: 'Creature Types' },
  { label: 'Inquisitor', value: 'Inquisitor', group: 'Creature Types' },
  { label: 'Insect', value: 'Insect', group: 'Creature Types' },
  { label: 'Jackal', value: 'Jackal', group: 'Creature Types' },
  { label: 'Jellyfish', value: 'Jellyfish', group: 'Creature Types' },
  { label: 'Judge', value: 'Judge', group: 'Creature Types' },
  { label: 'Juggernaut', value: 'Juggernaut', group: 'Creature Types' },
  { label: 'Kangaroo', value: 'Kangaroo', group: 'Creature Types' },
  { label: 'Kavu', value: 'Kavu', group: 'Creature Types' },
  { label: 'Killbot', value: 'Killbot', group: 'Creature Types' },
  { label: 'Kirin', value: 'Kirin', group: 'Creature Types' },
  { label: 'Kithkin', value: 'Kithkin', group: 'Creature Types' },
  { label: 'Knight', value: 'Knight', group: 'Creature Types' },
  { label: 'Kobold', value: 'Kobold', group: 'Creature Types' },
  { label: 'Kor', value: 'Kor', group: 'Creature Types' },
  { label: 'Kraken', value: 'Kraken', group: 'Creature Types' },
  { label: 'Lady', value: 'Lady', group: 'Creature Types' },
  { label: 'Lamia', value: 'Lamia', group: 'Creature Types' },
  { label: 'Lammasu', value: 'Lammasu', group: 'Creature Types' },
  { label: 'Leech', value: 'Leech', group: 'Creature Types' },
  { label: 'Leviathan', value: 'Leviathan', group: 'Creature Types' },
  { label: 'Lhurgoyf', value: 'Lhurgoyf', group: 'Creature Types' },
  { label: 'Licid', value: 'Licid', group: 'Creature Types' },
  { label: 'Lizard', value: 'Lizard', group: 'Creature Types' },
  { label: 'Lobster', value: 'Lobster', group: 'Creature Types' },
  { label: 'Mammoth', value: 'Mammoth', group: 'Creature Types' },
  { label: 'Manticore', value: 'Manticore', group: 'Creature Types' },
  { label: 'Masticore', value: 'Masticore', group: 'Creature Types' },
  { label: 'Mercenary', value: 'Mercenary', group: 'Creature Types' },
  { label: 'Merfolk', value: 'Merfolk', group: 'Creature Types' },
  { label: 'Metathran', value: 'Metathran', group: 'Creature Types' },
  { label: 'Mime', value: 'Mime', group: 'Creature Types' },
  { label: 'Minion', value: 'Minion', group: 'Creature Types' },
  { label: 'Minotaur', value: 'Minotaur', group: 'Creature Types' },
  { label: 'Mite', value: 'Mite', group: 'Creature Types' },
  { label: 'Mole', value: 'Mole', group: 'Creature Types' },
  { label: 'Monger', value: 'Monger', group: 'Creature Types' },
  { label: 'Mongoose', value: 'Mongoose', group: 'Creature Types' },
  { label: 'Monk', value: 'Monk', group: 'Creature Types' },
  { label: 'Monkey', value: 'Monkey', group: 'Creature Types' },
  { label: 'Moonfolk', value: 'Moonfolk', group: 'Creature Types' },
  { label: 'Mount', value: 'Mount', group: 'Creature Types' },
  { label: 'Mouse', value: 'Mouse', group: 'Creature Types' },
  { label: 'Mummy', value: 'Mummy', group: 'Creature Types' },
  { label: 'Mutant', value: 'Mutant', group: 'Creature Types' },
  { label: 'Myr', value: 'Myr', group: 'Creature Types' },
  { label: 'Mystic', value: 'Mystic', group: 'Creature Types' },
  { label: 'Naga', value: 'Naga', group: 'Creature Types' },
  { label: 'Nastiest,', value: 'Nastiest,', group: 'Creature Types' },
  { label: 'Nautilus', value: 'Nautilus', group: 'Creature Types' },
  { label: 'Necron', value: 'Necron', group: 'Creature Types' },
  { label: 'Nephilim', value: 'Nephilim', group: 'Creature Types' },
  { label: 'Nightmare', value: 'Nightmare', group: 'Creature Types' },
  { label: 'Nightstalker', value: 'Nightstalker', group: 'Creature Types' },
  { label: 'Ninja', value: 'Ninja', group: 'Creature Types' },
  { label: 'Noble', value: 'Noble', group: 'Creature Types' },
  { label: 'Noggle', value: 'Noggle', group: 'Creature Types' },
  { label: 'Nomad', value: 'Nomad', group: 'Creature Types' },
  { label: 'Nymph', value: 'Nymph', group: 'Creature Types' },
  { label: 'Octopus', value: 'Octopus', group: 'Creature Types' },
  { label: 'Ogre', value: 'Ogre', group: 'Creature Types' },
  { label: 'Ooze', value: 'Ooze', group: 'Creature Types' },
  { label: 'Orb', value: 'Orb', group: 'Creature Types' },
  { label: 'Orc', value: 'Orc', group: 'Creature Types' },
  { label: 'Orgg', value: 'Orgg', group: 'Creature Types' },
  { label: 'Otter', value: 'Otter', group: 'Creature Types' },
  { label: 'Ouphe', value: 'Ouphe', group: 'Creature Types' },
  { label: 'Ox', value: 'Ox', group: 'Creature Types' },
  { label: 'Oyster', value: 'Oyster', group: 'Creature Types' },
  { label: 'Pangolin', value: 'Pangolin', group: 'Creature Types' },
  { label: 'Paratrooper', value: 'Paratrooper', group: 'Creature Types' },
  { label: 'Peasant', value: 'Peasant', group: 'Creature Types' },
  { label: 'Pegasus', value: 'Pegasus', group: 'Creature Types' },
  { label: 'Pentavite', value: 'Pentavite', group: 'Creature Types' },
  { label: 'Performer', value: 'Performer', group: 'Creature Types' },
  { label: 'Pest', value: 'Pest', group: 'Creature Types' },
  { label: 'Phelddagrif', value: 'Phelddagrif', group: 'Creature Types' },
  { label: 'Phoenix', value: 'Phoenix', group: 'Creature Types' },
  { label: 'Phyrexian', value: 'Phyrexian', group: 'Creature Types' },
  { label: 'Pilot', value: 'Pilot', group: 'Creature Types' },
  { label: 'Pincher', value: 'Pincher', group: 'Creature Types' },
  { label: 'Pirate', value: 'Pirate', group: 'Creature Types' },
  { label: 'Plant', value: 'Plant', group: 'Creature Types' },
  { label: 'Pony', value: 'Pony', group: 'Creature Types' },
  { label: 'Porcupine', value: 'Porcupine', group: 'Creature Types' },
  { label: 'Possum', value: 'Possum', group: 'Creature Types' },
  { label: 'Praetor', value: 'Praetor', group: 'Creature Types' },
  { label: 'Primarch', value: 'Primarch', group: 'Creature Types' },
  { label: 'Prism', value: 'Prism', group: 'Creature Types' },
  { label: 'Processor', value: 'Processor', group: 'Creature Types' },
  { label: 'Proper', value: 'Proper', group: 'Creature Types' },
  { label: 'Rabbit', value: 'Rabbit', group: 'Creature Types' },
  { label: 'Raccoon', value: 'Raccoon', group: 'Creature Types' },
  { label: 'Ranger', value: 'Ranger', group: 'Creature Types' },
  { label: 'Rat', value: 'Rat', group: 'Creature Types' },
  { label: 'Rebel', value: 'Rebel', group: 'Creature Types' },
  { label: 'Reflection', value: 'Reflection', group: 'Creature Types' },
  { label: 'Reveler', value: 'Reveler', group: 'Creature Types' },
  { label: 'Rhino', value: 'Rhino', group: 'Creature Types' },
  { label: 'Rigger', value: 'Rigger', group: 'Creature Types' },
  { label: 'Robot', value: 'Robot', group: 'Creature Types' },
  { label: 'Rogue', value: 'Rogue', group: 'Creature Types' },
  { label: 'Rukh', value: 'Rukh', group: 'Creature Types' },
  { label: 'Sable', value: 'Sable', group: 'Creature Types' },
  { label: 'Salamander', value: 'Salamander', group: 'Creature Types' },
  { label: 'Samurai', value: 'Samurai', group: 'Creature Types' },
  { label: 'Sand', value: 'Sand', group: 'Creature Types' },
  { label: 'Saproling', value: 'Saproling', group: 'Creature Types' },
  { label: 'Satyr', value: 'Satyr', group: 'Creature Types' },
  { label: 'Scarecrow', value: 'Scarecrow', group: 'Creature Types' },
  { label: 'Scientist', value: 'Scientist', group: 'Creature Types' },
  { label: 'Scion', value: 'Scion', group: 'Creature Types' },
  { label: 'Scorpion', value: 'Scorpion', group: 'Creature Types' },
  { label: 'Scout', value: 'Scout', group: 'Creature Types' },
  { label: 'Sculpture', value: 'Sculpture', group: 'Creature Types' },
  { label: 'Serf', value: 'Serf', group: 'Creature Types' },
  { label: 'Serpent', value: 'Serpent', group: 'Creature Types' },
  { label: 'Servo', value: 'Servo', group: 'Creature Types' },
  { label: 'Shade', value: 'Shade', group: 'Creature Types' },
  { label: 'Shaman', value: 'Shaman', group: 'Creature Types' },
  { label: 'Shapeshifter', value: 'Shapeshifter', group: 'Creature Types' },
  { label: 'Shark', value: 'Shark', group: 'Creature Types' },
  { label: 'Sheep', value: 'Sheep', group: 'Creature Types' },
  { label: 'Ship', value: 'Ship', group: 'Creature Types' },
  { label: 'Siren', value: 'Siren', group: 'Creature Types' },
  { label: 'Skeleton', value: 'Skeleton', group: 'Creature Types' },
  { label: 'Skunk', value: 'Skunk', group: 'Creature Types' },
  { label: 'Slith', value: 'Slith', group: 'Creature Types' },
  { label: 'Sliver', value: 'Sliver', group: 'Creature Types' },
  { label: 'Sloth', value: 'Sloth', group: 'Creature Types' },
  { label: 'Slug', value: 'Slug', group: 'Creature Types' },
  { label: 'Snail', value: 'Snail', group: 'Creature Types' },
  { label: 'Snake', value: 'Snake', group: 'Creature Types' },
  { label: 'Soldier', value: 'Soldier', group: 'Creature Types' },
  { label: 'Soltari', value: 'Soltari', group: 'Creature Types' },
  { label: 'Spawn', value: 'Spawn', group: 'Creature Types' },
  { label: 'Specter', value: 'Specter', group: 'Creature Types' },
  { label: 'Spellshaper', value: 'Spellshaper', group: 'Creature Types' },
  { label: 'Sphinx', value: 'Sphinx', group: 'Creature Types' },
  { label: 'Spider', value: 'Spider', group: 'Creature Types' },
  { label: 'Spike', value: 'Spike', group: 'Creature Types' },
  { label: 'Spirit', value: 'Spirit', group: 'Creature Types' },
  { label: 'Splinter', value: 'Splinter', group: 'Creature Types' },
  { label: 'Sponge', value: 'Sponge', group: 'Creature Types' },
  { label: 'Spuzzem', value: 'Spuzzem', group: 'Creature Types' },
  { label: 'Spy', value: 'Spy', group: 'Creature Types' },
  { label: 'Squid', value: 'Squid', group: 'Creature Types' },
  { label: 'Squirrel', value: 'Squirrel', group: 'Creature Types' },
  { label: 'Starfish', value: 'Starfish', group: 'Creature Types' },
  { label: 'Surrakar', value: 'Surrakar', group: 'Creature Types' },
  { label: 'Survivor', value: 'Survivor', group: 'Creature Types' },
  { label: 'Synth', value: 'Synth', group: 'Creature Types' },
  { label: 'Teddy', value: 'Teddy', group: 'Creature Types' },
  { label: 'Tentacle', value: 'Tentacle', group: 'Creature Types' },
  { label: 'Tetravite', value: 'Tetravite', group: 'Creature Types' },
  { label: 'Thalakos', value: 'Thalakos', group: 'Creature Types' },
  { label: 'The', value: 'The', group: 'Creature Types' },
  { label: 'Thopter', value: 'Thopter', group: 'Creature Types' },
  { label: 'Thrull', value: 'Thrull', group: 'Creature Types' },
  { label: 'Tiefling', value: 'Tiefling', group: 'Creature Types' },
  { label: 'Time Lord', value: 'Time Lord', group: 'Creature Types' },
  { label: 'Townsfolk', value: 'Townsfolk', group: 'Creature Types' },
  { label: 'Toy', value: 'Toy', group: 'Creature Types' },
  { label: 'Tree', value: 'Tree', group: 'Creature Types' },
  { label: 'Treefolk', value: 'Treefolk', group: 'Creature Types' },
  { label: 'Trilobite', value: 'Trilobite', group: 'Creature Types' },
  { label: 'Triskelavite', value: 'Triskelavite', group: 'Creature Types' },
  { label: 'Troll', value: 'Troll', group: 'Creature Types' },
  { label: 'Turtle', value: 'Turtle', group: 'Creature Types' },
  { label: 'Tyranid', value: 'Tyranid', group: 'Creature Types' },
  { label: 'Unicorn', value: 'Unicorn', group: 'Creature Types' },
  { label: 'Urzan', value: 'Urzan', group: 'Creature Types' },
  { label: 'Vampire', value: 'Vampire', group: 'Creature Types' },
  { label: 'Vampyre', value: 'Vampyre', group: 'Creature Types' },
  { label: 'Varmint', value: 'Varmint', group: 'Creature Types' },
  { label: 'Vedalken', value: 'Vedalken', group: 'Creature Types' },
  { label: 'Villain', value: 'Villain', group: 'Creature Types' },
  { label: 'Volver', value: 'Volver', group: 'Creature Types' },
  { label: 'Waiter', value: 'Waiter', group: 'Creature Types' },
  { label: 'Wall', value: 'Wall', group: 'Creature Types' },
  { label: 'Walrus', value: 'Walrus', group: 'Creature Types' },
  { label: 'Warlock', value: 'Warlock', group: 'Creature Types' },
  { label: 'Warrior', value: 'Warrior', group: 'Creature Types' },
  { label: 'Wasp', value: 'Wasp', group: 'Creature Types' },
  { label: 'Weasel', value: 'Weasel', group: 'Creature Types' },
  { label: 'Weird', value: 'Weird', group: 'Creature Types' },
  { label: 'Werewolf', value: 'Werewolf', group: 'Creature Types' },
  { label: 'Whale', value: 'Whale', group: 'Creature Types' },
  { label: 'Wizard', value: 'Wizard', group: 'Creature Types' },
  { label: 'Wolf', value: 'Wolf', group: 'Creature Types' },
  { label: 'Wolverine', value: 'Wolverine', group: 'Creature Types' },
  { label: 'Wombat', value: 'Wombat', group: 'Creature Types' },
  { label: 'Worm', value: 'Worm', group: 'Creature Types' },
  { label: 'Wraith', value: 'Wraith', group: 'Creature Types' },
  { label: 'Wrestler', value: 'Wrestler', group: 'Creature Types' },
  { label: 'Wurm', value: 'Wurm', group: 'Creature Types' },
  { label: 'Yeti', value: 'Yeti', group: 'Creature Types' },
  { label: 'Zombie', value: 'Zombie', group: 'Creature Types' },
  { label: 'Zonian', value: 'Zonian', group: 'Creature Types' },
  { label: 'Zubera', value: 'Zubera', group: 'Creature Types' },
  { label: 'Alara', value: 'Alara', group: 'Planar Types' },
  { label: 'Alfava Metraxis', value: 'Alfava Metraxis', group: 'Planar Types' },
  { label: 'Amonkhet', value: 'Amonkhet', group: 'Planar Types' },
  { label: 'Amsterdam', value: 'Amsterdam', group: 'Planar Types' },
  { label: 'Androzani Minor', value: 'Androzani Minor', group: 'Planar Types' },
  { label: 'Antausia', value: 'Antausia', group: 'Planar Types' },
  { label: 'Apalapucia', value: 'Apalapucia', group: 'Planar Types' },
  { label: 'Arcavios', value: 'Arcavios', group: 'Planar Types' },
  { label: 'Arkhos', value: 'Arkhos', group: 'Planar Types' },
  { label: 'Azgol', value: 'Azgol', group: 'Planar Types' },
  { label: 'Belenon', value: 'Belenon', group: 'Planar Types' },
  { label: 'Blind Eternities', value: 'Blind Eternities', group: 'Planar Types' },
  { label: "Bolas's Meditation Realm", value: "Bolas's Meditation Realm", group: 'Planar Types' },
  { label: 'Capenna', value: 'Capenna', group: 'Planar Types' },
  { label: 'Chicago', value: 'Chicago', group: 'Planar Types' },
  { label: 'Cridhe', value: 'Cridhe', group: 'Planar Types' },
  { label: 'Darillium', value: 'Darillium', group: 'Planar Types' },
  { label: 'Dominaria', value: 'Dominaria', group: 'Planar Types' },
  { label: 'Earth', value: 'Earth', group: 'Planar Types' },
  { label: 'Echoir', value: 'Echoir', group: 'Planar Types' },
  { label: 'Eldraine', value: 'Eldraine', group: 'Planar Types' },
  { label: 'Equilor', value: 'Equilor', group: 'Planar Types' },
  { label: 'Ergamon', value: 'Ergamon', group: 'Planar Types' },
  { label: 'Fabacin', value: 'Fabacin', group: 'Planar Types' },
  { label: 'Fiora', value: 'Fiora', group: 'Planar Types' },
  { label: 'Foldaria', value: 'Foldaria', group: 'Planar Types' },
  { label: 'Gallifrey', value: 'Gallifrey', group: 'Planar Types' },
  { label: 'Gargantikar', value: 'Gargantikar', group: 'Planar Types' },
  { label: 'Gobakhan', value: 'Gobakhan', group: 'Planar Types' },
  { label: 'Horsehead Nebula', value: 'Horsehead Nebula', group: 'Planar Types' },
  { label: 'Ikoria', value: 'Ikoria', group: 'Planar Types' },
  { label: 'Innistrad', value: 'Innistrad', group: 'Planar Types' },
  { label: 'Iquatana', value: 'Iquatana', group: 'Planar Types' },
  { label: 'Ir', value: 'Ir', group: 'Planar Types' },
  { label: 'Ixalan', value: 'Ixalan', group: 'Planar Types' },
  { label: 'Kaladesh', value: 'Kaladesh', group: 'Planar Types' },
  { label: 'Kaldheim', value: 'Kaldheim', group: 'Planar Types' },
  { label: 'Kamigawa', value: 'Kamigawa', group: 'Planar Types' },
  { label: 'Kandoka', value: 'Kandoka', group: 'Planar Types' },
  { label: 'Karsus', value: 'Karsus', group: 'Planar Types' },
  { label: 'Kephalai', value: 'Kephalai', group: 'Planar Types' },
  { label: 'Kinshala', value: 'Kinshala', group: 'Planar Types' },
  { label: 'Kolbahan', value: 'Kolbahan', group: 'Planar Types' },
  { label: 'Kylem', value: 'Kylem', group: 'Planar Types' },
  { label: 'Kyneth', value: 'Kyneth', group: 'Planar Types' },
  { label: 'Lorwyn', value: 'Lorwyn', group: 'Planar Types' },
  { label: 'Luvion', value: 'Luvion', group: 'Planar Types' },
  { label: 'MagicCon', value: 'MagicCon', group: 'Planar Types' },
  { label: 'Mars', value: 'Mars', group: 'Planar Types' },
  { label: 'Mercadia', value: 'Mercadia', group: 'Planar Types' },
  { label: 'Mirrodin', value: 'Mirrodin', group: 'Planar Types' },
  { label: 'Moag', value: 'Moag', group: 'Planar Types' },
  { label: 'Mongseng', value: 'Mongseng', group: 'Planar Types' },
  { label: 'Moon', value: 'Moon', group: 'Planar Types' },
  { label: 'Muraganda', value: 'Muraganda', group: 'Planar Types' },
  { label: 'Necros', value: 'Necros', group: 'Planar Types' },
  { label: 'New Earth', value: 'New Earth', group: 'Planar Types' },
  { label: 'New Phyrexia', value: 'New Phyrexia', group: 'Planar Types' },
  { label: "Outside Mutter's Spiral", value: "Outside Mutter's Spiral", group: 'Planar Types' },
  { label: 'Phyrexia', value: 'Phyrexia', group: 'Planar Types' },
  { label: 'Pyrulea', value: 'Pyrulea', group: 'Planar Types' },
  { label: 'Rabiah', value: 'Rabiah', group: 'Planar Types' },
  { label: 'Rath', value: 'Rath', group: 'Planar Types' },
  { label: 'Ravnica', value: 'Ravnica', group: 'Planar Types' },
  { label: 'Regatha', value: 'Regatha', group: 'Planar Types' },
  { label: 'Segovia', value: 'Segovia', group: 'Planar Types' },
  { label: 'Serra’s Realm', value: 'Serra’s Realm', group: 'Planar Types' },
  { label: 'Shadowmoor', value: 'Shadowmoor', group: 'Planar Types' },
  { label: 'Shandalar', value: 'Shandalar', group: 'Planar Types' },
  { label: 'Shenmeng', value: 'Shenmeng', group: 'Planar Types' },
  { label: 'Skaro', value: 'Skaro', group: 'Planar Types' },
  { label: 'Spacecraft', value: 'Spacecraft', group: 'Planar Types' },
  { label: 'Tarkir', value: 'Tarkir', group: 'Planar Types' },
  { label: 'The Abyss', value: 'The Abyss', group: 'Planar Types' },
  { label: 'The Dalek Asylum', value: 'The Dalek Asylum', group: 'Planar Types' },
  { label: 'The Library', value: 'The Library', group: 'Planar Types' },
  { label: 'Theros', value: 'Theros', group: 'Planar Types' },
  { label: 'Time', value: 'Time', group: 'Planar Types' },
  { label: 'Trenzalore', value: 'Trenzalore', group: 'Planar Types' },
  { label: 'Ulgrotha', value: 'Ulgrotha', group: 'Planar Types' },
  { label: 'Unknown Planet', value: 'Unknown Planet', group: 'Planar Types' },
  { label: 'Valla', value: 'Valla', group: 'Planar Types' },
  { label: 'Vryn', value: 'Vryn', group: 'Planar Types' },
  { label: 'Wildfire', value: 'Wildfire', group: 'Planar Types' },
  { label: 'Xerex', value: 'Xerex', group: 'Planar Types' },
  { label: 'Zendikar', value: 'Zendikar', group: 'Planar Types' },
  { label: 'Zhalfir', value: 'Zhalfir', group: 'Planar Types' },
];

interface RarityType {
  label: string;
  value: string;
}

export const cardRarity: RarityType[] = [
  { label: 'Common', value: 'common'},
  { label: 'Uncommon', value: 'uncommon'},
  { label: 'Rare', value: 'rare'},
  { label: 'Mythic', value: 'mythic'},
  { label: 'Bonus', value: 'bonus'},
]

export const formatLegalities: RarityType[] = [
  { label: 'Standard', value: 'standard'},
  { label: 'Future', value: 'future'},
  { label: 'Historic', value: 'historic'},
  { label: 'Timeless', value: 'timeless'},
  { label: 'Gladiator', value: 'gladiator'},
  { label: 'Pioneer', value: 'pioneer'},
  { label: 'Explorer', value: 'explorer'},
  { label: 'Modern', value: 'modern'},
  { label: 'Legacy', value: 'legacy'},
  { label: 'Pauper', value: 'pauper'},
  { label: 'Vintage', value: 'vintage'},
  { label: 'Penny', value: 'penny'},
  { label: 'Commander', value: 'commander'},
  { label: 'Oathbreaker', value: 'oathbreaker'},
  { label: 'Standard Brawl', value: 'standardbrawl'},
  { label: 'alchemy', value: 'alchemy'},
  { label: 'Pauper Commander', value: 'paupercommander'},
  { label: 'Duel (Commander)', value: 'duel'},
  { label: 'Oldschool 93/94', value: 'oldschool'},
  { label: 'Premodern', value: 'premodern'},
  { label: 'Predh', value: 'predh'},
  { label: 'Brawl', value: 'brawl'}
]

// export const uniqueTypes: RarityType[] = [
//   { label: 'Cards', value: 'cards'},
//   { label: 'Prints', value: 'prints'},
//   { label: 'Art', value: 'art'}
// ]
//
// export const sortTypes: RarityType[] = [
//   { label: 'Artist', value: 'artist'},
//   { label: 'CMC', value: 'cmc'},
//   { label: 'Power', value: 'power'},
//   { label: 'Toughness', value: 'toughness'},
//   { label: 'Set', value: 'set'},
//   { label: 'Name', value: 'name'},
//   { label: 'USD', value: 'usd'},
//   { label: 'TIX', value: 'tix'},
//   { label: 'EUR', value: 'eur'},
//   { label: 'Rarity', value: 'rarity'},
//   { label: 'Color', value: 'color'},
//   { label: 'Released', value: 'released'},
//   { label: 'Spoiled', value: 'spoiled'},
//   { label: 'EDHREC', value: 'edhrec'},
//   { label: 'Penny', value: 'penny'},
//   { label: 'Review', value: 'review'}
// ]
//
// export const preferTypes: RarityType[] = [
//   { label: 'Oldest', value: 'oldest'},
//   { label: 'Newest', value: 'newest'},
//   { label: 'USD Low', value: 'usd-low'},
//   { label: 'USD High', value: 'usd-high'},
//   { label: 'TIX Low', value: 'tix-low'},
//   { label: 'TIX High', value: 'tix-high'},
//   { label: 'EUR Low', value: 'eur-low'},
//   { label: 'EUR High', value: 'eur-high'},
//   { label: 'Promo', value: 'promo'}
// ]
